[workspace]
members = [
    "engine/cli",
    "engine/core",
    "engine/phase10t",
    "engine/usi",
    "engine/wasm",
]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.89"
license = "AGPL-3.0-only"
authors = ["OpenShogiAI contributors"]

[workspace.dependencies]
open-shogi-core = { path = "engine/core", default-features = false }
open-shogi-usi = { path = "engine/usi", default-features = false }
proptest = "1"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
